version: "3.8"

services:
  comfyui_hybrid:
    build:
      context: .
      dockerfile: dockerfile_comfyuihybrid
    image: comfyui_hybrid:latest
    container_name: comfyui_hybrid
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8188:8188"
    volumes:
      # Map local directories to container paths
      - ../ComfyUI/models:/workspace/ComfyUI/models
      - ../ComfyUI/custom_nodes:/workspace/ComfyUI/custom_nodes
      - ../ComfyUI/input:/workspace/ComfyUI/input
      - ../ComfyUI/output:/workspace/ComfyUI/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
